/* Named re-exports - no wildcard barrels (project convention) */

export type {
  CreateHIP4AdapterConfig,
  HIP4ClientConfig,
  HIP4Signer,
  HLCancelResponse,
  HLCancelStatus,
  HLCandle,
  HLExtraAgent,
  HLFill,
  HLMergeOutcomeAction,
  HLMergeQuestionAction,
  HLNegateOutcomeAction,
  HLOutcome,
  HLOutcomeMeta,
  HLQuestion,
  HLReferralState,
  HLScheduleCancelAction,
  HLSettledOutcome,
  HLSignature,
  HLSpotClearinghouseState,
  HLSplitOutcomeAction,
  HLUserAbstraction,
  HLUserFees,
  HLUserOutcomeAction,
  HLUserRoleResponse,
  HLWsActivePerpAssetCtxData,
  HLWsActiveSpotAssetCtxData,
  HLWsAllMidsData,
  HLWsBboData,
  HLWsClearinghouseStateEvent,
  HLWsL2BookData,
  HLWsOpenOrdersEvent,
  HLWsOutcomeMetaSideSpec,
  HLWsOutcomeMetaUpdate,
  HLWsOutcomeMetaUpdates,
  HLWsOutcomeSpec,
  HLWsQuestionSpec,
  HLWsSpotAssetCtxItem,
  HLWsSpotAssetCtxsData,
  HLWsSpotStateEvent,
  HLWsTradesEvent,
  HLWsUserFillsEvent,
  MergeOutcomeParams,
  MergeQuestionParams,
  NegateOutcomeParams,
  ParsedDescription,
  ParsedPriceBucketDescription,
  PredictionAccountAdapter,
  PredictionAuthAdapter,
  PredictionEventAdapter,
  PredictionMarketDataAdapter,
  PredictionsAdapter,
  PredictionTradingAdapter,
  PredictionWalletAdapter,
  PriceBinaryMarket,
  QuestionIndex,
  SplitOutcomeParams,
  SpotSendParams,
  Unsubscribe,
  UsdClassTransferParams,
  UsdSendParams,
  WalletActionResult,
  WithdrawParams,
} from "./adapter";
/* v2: Pricing utilities */
/* v2: Market discovery */
/* v2: Market classification */
/* v2: Coin helpers */
export {
  buildQuestionIndex,
  classifyAllOutcomes,
  classifyOutcome,
  computeTickSize,
  createHIP4Adapter,
  discoverPriceBinaryMarkets,
  formatMarketLabel,
  formatPredictionPrice,
  formatPrice,
  ALL_DEXS,
  getAgentApprovalTypedData,
  getBuilderFeeApprovalTypedData,
  getMinShares,
  getPriceBucketBounds,
  HIP4Client,
  HIP4EventAdapter,
  HIP4TradingAdapter,
  HIP4WalletAdapter,
  HLApiError,
  isUsdClassTransferRequired,
  MIN_NOTIONAL,
  normalizeSignature,
  outcomeCoin,
  parseDescription,
  parsePriceBucketDescription,
  parseOutcomeCoin,
  parseSideCoin,
  periodMinutes,
  roundToTick,
  sideAssetId,
  sideCoin,
  splitHexSignature,
  stripZeros,
  submitAgentApproval,
  submitBuilderFeeApproval,
  timeToExpiry,
  USDC_HL_TOKEN_MAINNET,
  USDC_HL_TOKEN_TESTNET,
  USDH_ASSET_ID,
  USDH_ASSET_ID_MAINNET,
  USDH_ASSET_ID_TESTNET,
  USDH_CORE_DECIMALS,
  USDH_EVM_ADDRESS_MAINNET,
  USDH_EVM_ADDRESS_TESTNET,
  USDH_EVM_DECIMALS,
  USDH_HL_TOKEN_MAINNET,
  USDH_HL_TOKEN_TESTNET,
  USDH_SPOT_INDEX_MAINNET,
  USDH_SPOT_INDEX_TESTNET,
  USDH_SPOT_PAIR,
  USDH_SPOT_PAIR_MAINNET,
  USDH_SPOT_PAIR_TESTNET,
  USDH_TOKEN_HASH_MAINNET,
  USDH_TOKEN_HASH_TESTNET,
  USDH_TOKEN_INDEX_MAINNET,
  USDH_TOKEN_INDEX_TESTNET,
  deriveCoreEvmSystemAddress,
  HYPE_CORE_EVM_SYSTEM_ADDRESS,
  MAX_CORE_EVM_TOKEN_INDEX,
  CORE_TO_EVM_GAS_LIMIT,
  estimateCoreToEvmFee,
  medianBaseFeeWei,
  type CoreToEvmFeeBreakdown,
  type CoreToEvmFeeInputs,
  findHypeUsdcSpotPairCoin,
  HYPE_USDC_SPOT_PAIR_MAINNET,
  HYPE_USDC_SPOT_PAIR_TESTNET,
  selectHypeSpotMarkPx,
  type SelectHypeSpotMarkPxOptions,
  type SpotMetaShape,
} from "./adapter";

/* Streams */
export type { PriceFeedCandle } from "./streams/candle-utils";
export {
  candleBoundaryMs,
  intervalToMs,
  processTick,
} from "./streams/candle-utils";
export type {
  PerpPriceFeedOptions,
  PerpPriceFeedSnapshot,
} from "./streams/perp-price-feed";
export { createPerpPriceFeed } from "./streams/perp-price-feed";
export type { PriceFeedOptions, PriceFeedSnapshot } from "./streams/price-feed";
export { createPriceFeed } from "./streams/price-feed";
export type {
  PredictionActivity,
  PredictionAuthState,
  PredictionPosition,
} from "./types/account";
/* Types */
export type {
  PredictionCategory,
  PredictionEvent,
  PredictionEventStatus,
  PredictionMarket,
  PredictionOutcome,
} from "./types/event";
/* v2: HIP4Market types */
export type {
  BaseMarket,
  DefaultBinaryMarket,
  FetchMarketsParams,
  FetchMarketsResult,
  HIP4Market,
  LabelledBinaryMarket,
  MarketSide,
  MarketsByQuestion,
  MarketsByType,
  MarketType,
  MultiOutcomeMarket,
  PriceBucketMarket,
} from "./types/hip4-market";
export type {
  PredictionOrderBook,
  PredictionOrderBookLevel,
  PredictionPrice,
  PredictionTrade,
} from "./types/market";
export type {
  PredictionCancelParams,
  PredictionModifyParams,
  PredictionOrderParams,
  PredictionOrderResult,
  PredictionBatchOrderResult,
} from "./types/trading";

/* Orderbook utilities */
export type { TradeCostResult } from "./utils/orderbook";
export {
  computeEstimatedCost,
  computePotentialReturn,
  computeTradeCost,
} from "./utils/orderbook";
